### ISSUE TITLE
Contentful SDK stopped working properly last weekend

### ISSUE THREAD

**Issue by PiotrWpl** [contentful/contentful.php#283]
Hi,

last weekend a webpage, which I created for my friends, stopped working. From what I can see in the Apache logs, it's something related to GuzzleHttp which is used by Contenful SDK. Everything is working properly when I disable the usage of your SDK. Any idea what's going on?

> [Mon Feb 24 17:54:51.064561 2020] [:error] [pid 4235:tid 140610006492928] [client 89.64.9.170:17312] PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\RequestException: cURL error 77:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:201, referer: https://melodysamssie.pl/samoyed.html

> [Mon Feb 24 17:54:51.076128 2020] [:error] [pid 4235:tid 140610006492928] [client 89.64.9.170:17312] Stack trace:, referer: https://melodysamssie.pl/samoyed.html

> [Mon Feb 24 17:54:51.076355 2020] [:error] [pid 4235:tid 140610006492928] [client 89.64.9.170:17312] #0 /public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array), referer: https://melodysamssie.pl/samoyed.html

> [Mon Feb 24 17:54:51.076632 2020] [:error] [pid 4235:tid 140610006492928] [client 89.64.9.170:17312] #1 /public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory)), referer: https://melodysamssie.pl/samoyed.html

> [Mon Feb 24 17:54:51.076902 2020] [:error] [pid 4235:tid 140610006492928] [client 89.64.9.170:17312] #2 /public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory)), referer: https://melodysamssie.pl/samoyed.html

> [Mon Feb 24 17:54:51.077053 2020] [:error] [pid 4235:tid 140610006492928] [client 89.64.9.170:17312] #3 /public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 201, referer: https://melodysamssie.pl/samoyed.html

I'm using Contenful SDK 4.1.3

Thanks in advance!

**Comment by pgrigoruta** [comment]
Hello, we are not seeing this issue in general. Can you try a couple of things:
 - execute the same code from another machine, i.e. your local, so to exclude any change in the server configuration?
 - provide a code example that showcases the problem?

**Comment by pgrigoruta** [comment]
Closing due to inactivity, feel free to re-open if you have new information.
